### ISSUE TITLE
kinematics, fkreq.tip_names.append('right_hand')？？？

### ISSUE THREAD

**Issue by qiuqium11** [RethinkRobotics/intera_sdk#107]
for ('right_hand')，Is there anything else that can be replaced ? how many?

**Comment by IanTheEngineer** [comment]
Any TF frame that is beyond 5 DOF is a valid tip_name. For example:
`right_l6, right_wrist, right_hand, right_hand_camera, right_gripper_base`, any gripper frames, or additional frames that you've added to the end effector. A visual example of valid frames:
![valid_ik_frames](https://user-images.githubusercontent.com/850874/36861976-866adfc0-1d53-11e8-895a-caed695dcb50.png)
