### ISSUE TITLE
Using intera_interface with Python3

### ISSUE THREAD

**Issue by harry-uglow** [RethinkRobotics/intera_sdk#153]
I'm trying to control the robot from a program that requires python3. Is it possible to use the intera_interface with python3? When I try to import intera_interface my code I get import errors because of course the import statements in intera_interface are not valid in python 3.

What is the best way to work around this?

**Comment by gerritschoe** [comment]
It is correct that intera_interface only works in Python 2. You can run a separate Python 2 node in parallel to your Python 3 code and then arrange the communication with a ROS service or a ROS topic (publisher/subscriber).

**Comment by DanielTakeshi** [comment]
Will there be any possibility of using Python3 to control the intera_interface, given that Python2 is deprecated?
