### ISSUE TITLE
Lights Interface using the IO Framework

### ISSUE THREAD

**Issue by IanTheEngineer** [RethinkRobotics/intera_sdk#52]
It would be nice to turn off and on each of the lights onboard the robot at will with the SDK interface. Preferably, this would be an `intera_interface` class.

**Comment by michaelschleiss** [comment]
How can I use the flashlight on the hand camera? It is possible to use it in Intra Studio but I cannot find this function in the SDK?

**Comment by IanTheEngineer** [comment]
You can strobe the light on the Cognex through the camera interface:
```
import rospy
rospy.init_node("cognex_flash")

import intera_interface

c = intera_interface.Cameras()
c.cameras_io['right_hand_camera']['interface'].set_signal_value('set_strobe', True)   # sets the camera to strobe
c.cameras_io['right_hand_camera']['interface'].set_signal_value('set_strobe', False) # turns off the strobe
```
