### ISSUE TITLE
joint_position_file_playback won't run

### ISSUE THREAD

**Issue by jarvisschultz** [RethinkRobotics/intera_sdk#90]
Example won't run because there are two definitions for the `-l` argument to the argparse parser. See [here](https://github.com/RethinkRobotics/intera_sdk/blob/bd11936c43769a604375359b7da64976c1bfac19/intera_examples/scripts/joint_position_file_playback.py#L148-L155). It's currently defined to be both which limb to use and how many times to loop the playback.

Very minor issue, but should probably be fixed.

**Comment by IanTheEngineer** [comment]
Thanks for the report, Jarvis! You're absolutely correct, this needs to be fixed.
