### ISSUE TITLE
ping successfully  but can not control sawyer robot by wifi

### ISSUE THREAD

**Issue by qiuqium11** [RethinkRobotics/intera_sdk#96]
we can control intera sdk by  wifi ,and we change the wifi to ethernet cable，we change our  robot to use "Automatic" addressing, and set other steps , it is successfully.
    but when we back to wifi connect , wrong coming, ping robot_hosname.local is successfully, but can not run all of the examples ,such as can not run rosrun intera_examples head_wobbler.py etc.

**Comment by rethink-mattKelly** [comment]
Try running the following command from a terminal that is on your host computer and targeted at the robot:
`export ROS_IP=<your_computer_IP_address>`
You can find `<your_computer_IP_address>` by running `ifconfig` at terminal and using the `inet addr: 192.168.*.*`
Not sure if it will work for you, but this fixes a similar problem for me.

**Comment by IanTheEngineer** [comment]
Controlling Sawyer (and using ROS) over wifi is entirely possible, but not an officially supported networking configuration for the SDK. The [basic Networking configuration](http://sdk.rethinkrobotics.com/intera/Networking#Network_Configuration_through_a_Router) is the same, but the possibility for more packets to be dropped increases. I would recommend following the networking tutorial above as if it is a regular ethernet router, and if you continue to have issues, ask for ROS networking help via answers.ros.org. Hope this helps!
